In [ ]:
# code written by Mayuri

In [ ]:

import pandas as pd

data1_2008 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2008")
data1_sheet1 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="Sheet1")
data1_2009 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2009 RECODE")
data1_2010 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2010")
data1_2011 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2011")
data1_2012 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2012")
data1_2013 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2013")
data1_2014 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2014")
data1_2015 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2015")
data1_2016 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2016")

In [ ]:
data2 = pd.read_excel("Human Trafficking Index Dataset")

 
print(data1_2008.shape)
print(data1_sheet1.shape)
print(data1_2009.shape)
print(data1_2010.shape)
print(data1_2008.shape)
print(data1_2008.shape)
print(data1_2008.shape)

### Code Written by Rosy

In [3]:
import pandas as pd
data1_2008 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2008")

In [4]:
data1_2008.head()

,2008,Origin Country,(Transit Country),Destination Country,Victim Profile,type of trafficking,Means,trafficker,Sector,Notes,Flagged
0,2008,Afghanistan,NaN,Pakistan,NaN,1.0,NaN,11.0,NaN,NaN,NaN
1,2008,Afghanistan,NaN,"Iran, Islamic Republic of",NaN,1.0,NaN,11.0,NaN,NaN,NaN
2,2008,Afghanistan,NaN,Saudi Arabia,NaN,1.0,NaN,11.0,NaN,NaN,NaN
3,2008,Afghanistan,NaN,Oman,NaN,1.0,NaN,11.0,NaN,NaN,NaN
4,2008,Afghanistan,NaN,Gulf States,NaN,NaN,NaN,NaN,NaN,NaN,X

In [5]:
data1_2008.columns

Index([                 2008,      'Origin Country',   '(Transit Country)',
       'Destination Country',      'Victim Profile', 'type of trafficking',
                     'Means',          'trafficker',              'Sector',
                     'Notes',             'Flagged'],
      dtype='object')

In [6]:
data1_2008['Origin Country'].unique()
data1_2008[(data1_2008['Origin Country']=='Neighboring countries')]

,2008,Origin Country,(Transit Country),Destination Country,Victim Profile,type of trafficking,Means,trafficker,Sector,Notes,Flagged
332,2008,Neighboring countries,NaN,Chile,NaN,1.0,1.0,11.0,NaN,NaN,X
544,2008,Neighboring countries,NaN,El Salvador,2.0,2.0,NaN,9.0,2,NaN,X
545,2008,Neighboring countries,NaN,El Salvador,3.0,2.0,NaN,9.0,2,NaN,X
546,2008,Neighboring countries,NaN,El Salvador,4.0,2.0,NaN,9.0,2,NaN,X
553,2008,Neighboring countries,NaN,Equatorial Guinea,1.0,1.0,NaN,11.0,NaN,NaN,X
616,2008,Neighboring countries,NaN,"Gambia, The",1.0,NaN,NaN,NaN,NaN,NaN,X
617,2008,Neighboring countries,NaN,"Gambia, The",3.0,NaN,NaN,NaN,NaN,NaN,X
618,2008,Neighboring countries,NaN,"Gambia, The",4.0,NaN,NaN,NaN,NaN,NaN,X
729,2008,Neighboring countries,NaN,Honduras,NaN,1.0,NaN,11.0,NaN,NaN,X
1613,2008,Neighboring countries,Tanzania,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,X
1614,2008,Neighboring countries,Tanzania,Europe,NaN,NaN,NaN,NaN,NaN,NaN,X
1615,2008,Neighboring countries,Tanzania,Middle East,NaN,NaN,NaN,NaN,NaN,NaN,X
1616,2008,Neighboring countries,Tanzania,NaN,NaN,3.0,NaN,NaN,NaN,NaN,X
1617,2008,Neighboring countries,Tanzania,NaN,NaN,1.0,NaN,11.0,NaN,NaN,X

To Plot the directed graph lets first find out the logitude and latitude of each country and save it in new columns 

Getting Logitude and Latitude of Each Countries

Note: To use Geocoder.

> We need to signup in http://www.geonames.org/

> Use the username for connecting to geopy

> Need to enable the user acount

In [7]:
from geopy import geocoders
from geopy.geocoders import Nominatim
gn = geocoders.GeoNames(username='rose0037')
geolocator = Nominatim()

Now Lets update the logitude and Latitude of each country.

In [13]:
location = geolocator.geocode("India")
print((location.latitude, location.longitude))

(22.3511148, 78.6677428)

In [9]:
data1_2008.head()

,2008,Origin Country,(Transit Country),Destination Country,Victim Profile,type of trafficking,Means,trafficker,Sector,Notes,Flagged
0,2008,Afghanistan,NaN,Pakistan,NaN,1.0,NaN,11.0,NaN,NaN,NaN
1,2008,Afghanistan,NaN,"Iran, Islamic Republic of",NaN,1.0,NaN,11.0,NaN,NaN,NaN
2,2008,Afghanistan,NaN,Saudi Arabia,NaN,1.0,NaN,11.0,NaN,NaN,NaN
3,2008,Afghanistan,NaN,Oman,NaN,1.0,NaN,11.0,NaN,NaN,NaN
4,2008,Afghanistan,NaN,Gulf States,NaN,NaN,NaN,NaN,NaN,NaN,X

In [14]:
data1_2008.dropna(subset=['Origin Country'], inplace=True)
data1_2008['Origin Country'].unique()

array(['Afghanistan', 'China', 'Iran, Islamic Republic of', 'Tajikistan',
       'Albania', 'Sub-Saharan Africa', 'Angola',
       'Congo, Democratic Republic of', 'Argentina', 'Paraguay', 'Brazil',
       'Dominican Republic', 'Armenia', 'Ukraine', 'Russian Federation',
       'Southeast Asia', 'Korea, Republic of', 'Taiwan, China', 'India',
       'Philippines', 'Ireland', 'Africa', 'Bulgaria', 'Romania',
       'Azerbaijan', 'Uzbekistan', 'Kyrgyz Republic', 'Kazakhstan',
       'Moldova', 'Pakistan', 'Nepal', 'Sri Lanka', 'Bangladesh',
       'Indonesia', 'Thailand', 'Ethiopia', 'Eritrea', 'Morocco',
       'Eastern Europe', 'Central Asia', 'Myanmar', 'Belarus', 'Nigeria',
       'Central America', 'Benin', 'Togo', 'Niger', 'Burkina Faso',
       'Bolivia', 'Asia', 'Serbia', 'Bosnia and Herzegovina', 'Peru',
       'Europe', 'United States', "Cote d'Ivoire", 'Mali', 'Ghana',
       'Burundi', 'Cambodia', 'Vietnam', 'Austria', 'Germany', 'Italy',
       'United Kingdom', 'Singapore', 'Chad', 'Central African Republic',
       'Congo', 'Cameroon', 'Latin America', 'Caribbean', 'Malaysia',
       'Rwanda', 'Guinea', 'Chile', 'Neighboring countries', 'Mongolia',
       "Korea, Democratic People's Republic of", 'Colombia', 'Uganda',
       'Senegal', 'Nicaragua', 'Panama', 'Costa Rica', 'North Africa',
       'Southeastern Europe', 'Canada', 'Cuba', 'Lebanon', 'Hungary',
       'Greece', 'Georgia', 'Denmark', 'France', 'Spain', 'Haiti',
       'Ecuador', 'Gulf States', 'Honduras', 'El Salvador', 'Gabon',
       'Estonia', 'South America', 'Sierra Leone', 'Liberia',
       'Guinea-Bissau', 'Gambia, The', 'Former Soviet states',
       'West Africa', 'Guatemala', 'Guyana', 'Suriname', 'Venezuela',
       'Australia', 'Egypt, Arab Republic of', 'Jordan', 'Turkey',
       'Israel', 'East Africa', 'Middle East', 'Poland', 'Jamaica',
       'Japan', 'East Asia', 'Kenya', 'Somalia', 'South Asia',
       "Laos, People's Democratic Republic", 'Latvia',
       'Syrian Arab Republic', 'Lithuania', 'Switzerland', 'Mauritius',
       'Reunion', 'Malawi', 'Zambia', 'Mozambique', 'Tanzania',
       'Western Europe', 'Mexico', 'Kosovo', 'Zimbabwe', 'Hong Kong',
       'Norway', 'Turkmenistan', 'Northeast Asia', 'North America',
       'Yemen, Republic of', 'Sudan',
       'Macedonia, Former Yugoslav Republic of', 'Croatia', 'Slovenia',
       'Slovak Republic', 'South Africa', 'Former Soviet Union', 'Iraq',
       'Region', 'Timor-Leste', 'Tunisia', 'Uruguay ', 'Lesotho',
       'Swaziland'], dtype=object)

<font color = red> Questions: 
1) Neighboring countries what does this mean.

2) Sub-Saharan Africa reaplces with Africa 

3) Former Soviet states replaced with soviate union 
</font>

### Populating source Logitude and Latitude

In [21]:
for country in data1_2008['Origin Country'].unique():
    if (country == "Sub-Saharan Africa"):
        location = geolocator.geocode("Africa")
    else:
        if (country == "Former Soviet states" or country == "Former Soviet Union" ):
            location = geolocator.geocode("Soviet union")
        else:
            if (country != "Neighboring countries"):
                location = geolocator.geocode(country)
    data1_2008.loc[(data1_2008['Origin Country']==country), 'Source_Latitude'] = location.latitude
    data1_2008.loc[(data1_2008['Origin Country']==country), 'Source_Longitude'] = location.longitude

GeocoderTimedOut: Service timed out

In [27]:
data1_2008

,2008,Origin Country,(Transit Country),Destination Country,Victim Profile,type of trafficking,Means,trafficker,Sector,Notes,Flagged,Source_Latitude,Source_Longitude,Destination_Latitude,Destination_Longitude
0,2008,Afghanistan,NaN,Pakistan,NaN,1.0,NaN,11.0,NaN,NaN,NaN,33.768006,66.238514,30.330840,71.247499
1,2008,Afghanistan,NaN,"Iran, Islamic Republic of",NaN,1.0,NaN,11.0,NaN,NaN,NaN,33.768006,66.238514,32.940750,52.947134
2,2008,Afghanistan,NaN,Saudi Arabia,NaN,1.0,NaN,11.0,NaN,NaN,NaN,33.768006,66.238514,13.968817,121.525087
3,2008,Afghanistan,NaN,Oman,NaN,1.0,NaN,11.0,NaN,NaN,NaN,33.768006,66.238514,25.227893,55.176669
4,2008,Afghanistan,NaN,Gulf States,NaN,NaN,NaN,NaN,NaN,NaN,X,33.768006,66.238514,42.710048,-71.441458
5,2008,Afghanistan,NaN,"Iran, Islamic Republic of",2.0,2.0,NaN,NaN,NaN,NaN,NaN,33.768006,66.238514,32.940750,52.947134
6,2008,China,NaN,Afghanistan,NaN,1.0,NaN,11.0,NaN,NaN,NaN,25.491580,-98.981112,33.768006,66.238514
7,2008,"Iran, Islamic Republic of",NaN,Afghanistan,NaN,1.0,NaN,11.0,NaN,NaN,NaN,32.940750,52.947134,33.768006,66.238514
8,2008,Tajikistan,NaN,Afghanistan,NaN,1.0,NaN,11.0,NaN,NaN,NaN,38.628173,70.815654,33.768006,66.238514
9,2008,Tajikistan,Afghanistan,Pakistan,NaN,1.0,NaN,11.0,NaN,NaN,NaN,38.628173,70.815654,30.330840,71.247499
10,2008,Tajikistan,Afghanistan,"Iran, Islamic Republic of",NaN,1.0,NaN,11.0,NaN,NaN,NaN,38.628173,70.815654,32.940750,52.947134
11,2008,Albania,NaN,Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,38.995368,21.987713
12,2008,Albania,NaN,Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,42.638426,12.674297
13,2008,Albania,NaN,"Macedonia, Former Yugoslav Republic of",NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,41.617121,21.716839
14,2008,Albania,NaN,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,42.586958,20.902123
15,2008,Albania,NaN,United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,25.223228,55.159493
16,2008,Albania,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,46.603354,1.888334
17,2008,Albania,NaN,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,50.640735,4.666960
18,2008,Albania,NaN,Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,64.573154,11.528036
19,2008,Albania,NaN,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,51.083420,10.423447
20,2008,Albania,NaN,Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,52.237989,5.534607
21,2008,Albania,NaN,Greece,3.0,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,38.995368,21.987713
22,2008,Albania,NaN,Greece,4.0,NaN,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,38.995368,21.987713
23,2008,Albania,NaN,Greece,NaN,2.0,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,38.995368,21.987713
24,2008,Albania,NaN,Greece,NaN,2.0,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,38.995368,21.987713
25,2008,Albania,NaN,Greece,NaN,6.0,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,38.995368,21.987713
26,2008,Albania,NaN,Greece,NaN,6.0,NaN,NaN,NaN,NaN,NaN,11.244883,-72.516099,38.995368,21.987713
27,2008,Sub-Saharan Africa,Algeria,Europe,1.0,NaN,NaN,NaN,NaN,NaN,X,2.000000,16.000000,51.000000,10.000000
28,2008,Sub-Saharan Africa,Algeria,Europe,2.0,NaN,NaN,NaN,NaN,NaN,X,2.000000,16.000000,51.000000,10.000000
29,2008,Sub-Saharan Africa,Algeria,Europe,NaN,1.0,NaN,11.0,NaN,NaN,X,2.000000,16.000000,51.000000,10.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1972,2008,Somalia,NaN,Malawi,3.0,NaN,NaN,NaN,NaN,NaN,NaN,-13.180556,15.266667,-13.268720,NaN
1973,2008,Somalia,NaN,Tanzania,3.0,NaN,NaN,NaN,NaN,NaN,NaN,-13.180556,15.266667,-6.524712,NaN
1974,2008,Somalia,NaN,Djibouti,4.0,NaN,NaN,NaN,NaN,NaN,NaN,-13.180556,15.266667,11.856775,NaN
1975,2008,Somalia,NaN,Malawi,4.0,NaN,NaN,NaN,NaN,NaN,NaN,-13.180556,15.266667,-13.268720,NaN
1976,2008,Somalia,NaN,Tanzania,4.0,NaN,NaN,NaN,NaN,NaN,NaN,-13.180556,15.266667,-6.524712,NaN
1977,2008,Ethiopia,Somalia,Middle East,1.0,NaN,NaN,NaN,NaN,NaN,X,10.211670,38.652120,32.186232,NaN
1978,2008,Cambodia,NaN,Somalia,2.0,2.0,NaN,9.0,6,NaN,NaN,13.506639,104.869423,-13.180556,NaN
1979,2008,Swaziland,NaN,South Africa,3.0,NaN,NaN,NaN,NaN,NaN,NaN,25.216549,55.181776,-28.816624,24.991639
1980,2008,Swaziland,NaN,Mozambique,3.0,NaN,NaN,NaN,NaN,NaN,NaN,25.216549,55.181776,19.058889,NaN
1981,2008,Swaziland,NaN,South Africa,1.0,1.0,NaN,11.0,NaN,NaN,NaN,25.216549,55.181776,-28.816624,24.991639
1982,2008,Swaziland,NaN,Mozambique,1.0,1.0,NaN,11.0,NaN,NaN,NaN,25.216549,55.181776,19.058889,NaN
1983,2008,Mozambique,NaN,Swaziland,1.0,1.0,NaN,11.0,NaN,NaN,NaN,19.058889,-96.254167,25.216549,NaN
1984,2008,Mozambique,Swaziland,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.058889,-96.254167,-28.816624,24.991639
1985,2008,Mozambique,NaN,Swaziland,4.0,2.0,NaN,NaN,NaN,NaN,NaN,19.058889,-96.254167,25.216549,NaN
1986,2008,Africa,Tunisia,Europe,NaN,NaN,NaN,NaN,NaN,NaN,X,2.000000,16.000000,51.000000,10.000000
1987,2008,Turkmenistan,NaN,Turkey,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,38.959759,34.924965
1988,2008,Turkmenistan,NaN,Algeria,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,28.000027,2.999983
1989,2008,Turkmenistan,NaN,Sudan,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,14.584444,NaN
1990,2008,Turkmenistan,NaN,Tunisia,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,33.843941,NaN
1991,2008,Turkmenistan,NaN,United Kingdom,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,25.223228,55.159493
1992,2008,Turkmenistan,NaN,Thailand,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,14.897192,NaN
1993,2008,Turkmenistan,NaN,United Arab Emirates,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,24.000249,53.999483
1994,2008,Turkmenistan,NaN,Cyprus,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,34.982302,NaN
1995,2008,Turkmenistan,NaN,Kazakhstan,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,47.228609,NaN
1996,2008,Turkmenistan,NaN,Kyrgyz Republic,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,41.508932,NaN
1997,2008,Turkmenistan,NaN,Pakistan,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,30.330840,71.247499
1998,2008,Turkmenistan,NaN,"Iran, Islamic Republic of",1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,32.940750,52.947134
1999,2008,Turkmenistan,NaN,Israel,1.0,1.0,NaN,11.0,NaN,NaN,NaN,39.376381,59.392461,30.876027,NaN
2000,2008,Turkmenistan,NaN,Turkey,1.0,3.0,NaN,NaN,NaN,NaN,NaN,39.376381,59.392461,38.959759,34.924965
2001,2008,Turkmenistan,NaN,Turkey,2.0,2.0,NaN,9.0,7,NaN,NaN,39.376381,59.392461,38.959759,34.924965

### Populating Destination Logitude and Latitude

In [26]:
for country in data1_2008['Destination Country'].unique():
    if (country == "Sub-Saharan Africa"):
        location = geolocator.geocode("Africa")
    else:
        if (country == "Former Soviet states" or country == "Former Soviet Union" ):
            location = geolocator.geocode("Soviet union")
        else:
            if (country != "Neighboring countries"):
                location = geolocator.geocode(country)
    data1_2008.loc[(data1_2008['Destination Country']==country), 'Destination_Latitude'] = location.latitude
  #  data1_2008.loc[(data1_2008['Destination Country']==country), 'Destination_Longitude'] = location.longitude

In [23]:
location = geolocator.geocode("Soviet union")
print((location.latitude, location.longitude))

(49.0530539, -122.3382208)

In [29]:
c = data1_2008.loc[(data1_2008['Origin Country']=='Afghanistan'), ['Origin Country','Destination Country','Destination_Latitude','Destination_Longitude','Source_Latitude','Source_Longitude']]

Lets plot the map from source as Afganistan to destination countries.

In [30]:
import pandas as pd
import requests
from xml.etree import ElementTree
import numpy as np
import folium

In [31]:
source_locations = c[['Source_Latitude', 'Source_Longitude']]
source_locations = source_locations.head(1)  ## As all the values are same , lets take only one value
destination_locations = c[['Destination_Latitude', 'Destination_Longitude']]
destination_locations_list = destination_locations.values.tolist()
source_locations

   Source_Latitude  Source_Longitude
0        33.768006         66.238514

##### Getting the unique destination locations

In [32]:
s = []
for i in destination_locations_list:
       if i not in s:
          s.append(i)
s

[[30.3308401, 71.247499],
 [32.9407496, 52.9471344],
 [13.9688165, 121.5250871],
 [25.22789295, 55.1766685144623],
 [42.710048, -71.4414585],
 [24.0002488, 53.9994829]]

In [43]:
c['Destination Country'].unique()

array(['Pakistan', 'Iran, Islamic Republic of', 'Saudi Arabia', 'Oman',
       'Gulf States', 'United Arab Emirates'], dtype=object)

In [48]:
map = folium.Map(location=[33.768006, 66.238514], tiles='Stamen Terrain', zoom_start=1)
for point in range(0, len(s)):
    folium.Marker(s[point], 
                  popup=c['Destination Country'][point]).add_to(map)
    
folium.Marker(
    location=[33.768006, 66.238514],
    popup='Mt. Hood Meadows',
    icon=folium.Icon(color='green')
).add_to(map)

map

In [37]:
#from folium.plugins import MarkerCluster

map2 = folium.Map(location=[33.768006, 66.238514], tiles='Stamen Terrain', zoom_start=1)
marker_cluster = MarkerCluster().add_to(map2)
for point in range(0, len(s)):
    folium.Marker(s[point], popup=c['Destination Country'][point], 
                  icon=folium.Icon(color='darkblue', 
                                   icon_color='white', 
                                   icon='male', 
                                   angle=0, 
                                   prefix='fa')).add_to(marker_cluster)
map2

NameError: name 'MarkerCluster' is not defined